create table funcionarios(
id_funcionario int not null,
nome_func varchar(40),
telefone char(20),
sexo varchar(11),
rg char(12),
cpf varchar(20),
estado_civil varchar(20),
uf varchar(30),
cidade varchar(30),
bairro varchar(30),
tipo varchar(30),
cep varchar(20),
num_casa int not null,
logradouro varchar(60),
senha varchar(15),
email varchar(60),
nivel integer not null,
data_nascimento varchar(15),
data_admissao varchar(30),
cargo varchar(20),
constraint pk_funcionarios primary key(id_funcionario))